### ISSUE TITLE
Question: how does the plugin work? :)

### ISSUE THREAD

**Issue by tomer-ben-david** [FracturedLoop/zazu-dash#3]
Hi, where is the code? i'm looking at: https://github.com/FracturedLoop/zazu-dash/blob/master/src/dash.js but i don't get the logic, does it go to dash somehow to look for content? where is the code? :)

**Comment by JosNun** [comment]
Dash supports a URL scheme:
<img width="311" alt="screen shot 2017-12-25 at 11 41 47 am" src="https://user-images.githubusercontent.com/7729878/34341595-a7c8ff7c-e968-11e7-84d8-63ae3996178b.png">

If you look at [zazu.json](https://github.com/FracturedLoop/zazu-dash/blob/master/zazu.json), You'll see that I just have Zazu running a search (line 21) using the Dash URL and the user's query.

**Comment by tomer-ben-david** [comment]
thanks, i get it now.
